### ISSUE TITLE
Telemetry keeps asking if I am interested on every reload

### ISSUE THREAD

**Issue by dschreij** [nuxt/telemetry#17]
Hi guys. Even though I am not opposed at all to collecting information for telemetry purposes, the module now asks for my permission every time the server is reloaded (e.g. Are you interested in participation (Y/n)). It does not remember my response, while I think it should?
I think the problem here is that I use Nuxt with Adonis as the backend (using the official Nuxt template for this). In this structure, the settings are not stored in `nuxt.config.js` but in `config/nuxt.js`. I assume that is where the telemetry module stores the response setting, and it may have difficulties with this non-default path for the settings file?

**Comment by dschreij** [comment]
I just found https://github.com/nuxt/telemetry/issues/16#issuecomment-647014318 in a closed issue. Maybe these (and other possible) settings should be mentioned the documentation/readme of this module.

**Comment by pi0** [comment]
Hi @dschreij. Thanks for reporting. This issue is probably because `.nuxtrc` cannot be read with programmatic (addonis) usage. I've added `telemetry: true` (as well as `telemetry: false`) support to nuxtconfig ([v1.2.0](https://github.com/nuxt/telemetry/releases/tag/v1.2.0))
