### ISSUE TITLE
.nuxtrc in $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by smhmd** [nuxt/telemetry#21]
Support placing `.nuxtrc` in `~/.config/nuxtrc` or `~/.config/nuxt/config` (or whatever `$XDG_CONFIG_HOME` is) as defined by [XDG Base Directory specification](https://wiki.archlinux.org/index.php/XDG_Base_Directory) (an attempt to declutter `$HOME`).

**Comment by pi0** [comment]
Hi @smhmd. We load `.nuxtrc` using [rc9](https://github.com/nuxt-contrib/rc9). Would be nice if you can make a PR to improve :)
