### ISSUE TITLE
Please...

### ISSUE THREAD

**Issue by tully4school** [nuxt/telemetry#25]
Could you please make it so i can put --yes or -y....i have been working on a project non stop for days and i have to keep stopping everything to type y. i want to help i really do, but maybe only ask like once a week? instead of on every build? its already long enough and, when you're working on a bug, u could reset it every minute. i really appreciate everything you're doing // have done. Thank you.

**Comment by pi0** [comment]
Hi @tully4school. Did you tried `npx nuxt telemetry disable --global`?

**Comment by tully4school** [comment]
You are awesome ill try it as soon as i get back :-) thank you so much

**Comment by tully4school** [comment]
excellent, thank you very very much pi0, using the last method of `telemetry: true` worked, i really appreciate it
