### ISSUE TITLE
Please support nodejs 8.x.x

### ISSUE THREAD

**Issue by hm496** [nuxt/telemetry#26]
The dependence fs-extra@9.0.1 only supports nodejs >= 10.0.0,
please replace one to support nodejs 8.x.x

**Comment by pi0** [comment]
Hi @hm496. Issue should be fixed by https://github.com/nuxt/telemetry/commit/b28d1cb01ecf4d17c4c61d8f68309a451c0ed2cd. you can use `yarn upgrade nuxt` to get latest dep
