### ISSUE TITLE
Remove Extensions Ads when Extension is Already Installed

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/telemetry#28]
It would be nice if the Extension ads were removed when you already have the extension installed.

![image](https://user-images.githubusercontent.com/2112282/92626775-ff8e9180-f28f-11ea-9428-83d85b7dc22d.png)

**Comment by DerekAlanGilbert** [comment]
I think the new vue telemetry extension and nuxt/telemetry and two different things.

**Comment by hecktarzuli** [comment]
They are!  One is a website, another is a Chrome/FF extension.  But, there may be ways for them to talk indirectly.

**Comment by hecktarzuli** [comment]
On second thought, I see what you mean.  I can't seem to find the real website to submit this... If I find it, I'll delete this.

**Comment by hecktarzuli** [comment]
Heck with it, I'll just fill out the feedback form on the site.
MOVING ON!

**Comment by DerekAlanGilbert** [comment]
I think I found it [here](https://github.com/nuxt-company/vue-telemetry-analyzer)!
