### ISSUE TITLE
i can't close it

### ISSUE THREAD

**Issue by ericzzhou** [nuxt/telemetry#54]
![image](https://user-images.githubusercontent.com/19791685/128291613-5ebf582d-4ce0-4dbd-bd2f-90e44b4b4e98.png)

  "nuxt": "^2.15.3",

**Comment by pi0** [comment]
Hi dear @ericzzhou. It is strange but might be also valid issue with IDE integration. If for any reason you cannot content with interactive prompts, please use one of the alternative opt-in/out methods mentioned here: https://github.com/nuxt/telemetry#opting-out
