### ISSUE TITLE
[v1] WARN  Module @nuxt/telemetry not found.

### ISSUE THREAD

**Issue by kaviraj-soni** [nuxt/telemetry#88]
Our Nuxt Builds are again failing
https://github.com/nuxt/telemetry/pull/85 after this PR is merged as it has breaking changes
Since rc9 was upgraded from 1.2.2 to 2.0.0 ( and 2.0.0 has breaking changes due to defu's breaking changes )
Please fix this ASAP
![image](https://user-images.githubusercontent.com/71137191/202169781-0db8b10b-3977-4b91-9048-c83f556aa5c5.png)

**Comment by AikateriniKyriakou** [comment]
Same problem here. 
![bugnuxt](https://user-images.githubusercontent.com/47486021/202171516-eccdcbd8-81fe-4631-8135-f6f42b0159bd.png)

**Comment by danielroe** [comment]
Are you on Nuxt 2?

**Comment by AikateriniKyriakou** [comment]
> Are you on Nuxt 2?

Yes, I have nuxt version 2.14.12

**Comment by kaviraj-soni** [comment]
> Are you on Nuxt 2?

Yes I am on Nuxt 2

**Comment by kaviraj-soni** [comment]
to quickly resolve this, we have disabled telemetry by adding this to our nuxt.config.js
`export default {
  telemetry: false
}`

**Comment by MiguelSantosMS** [comment]
That doesn't fix it for me

**Comment by AikateriniKyriakou** [comment]
> then you should be using v1 of `@nuxt/telemetry`.

The version 1.3.8 of @nuxt/telemetry generates this error. I tried downgrading to 1.3.7 and everything works ok.

**Comment by danielroe** [comment]
v1.3.8 still depends on ^1.2.0 of rc9: https://unpkg.com/browse/@nuxt/telemetry@1.3.8/package.json.

Would you provide a reproduction?

**Comment by hjardines** [comment]
Same problem here.

`npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /var/app/staging/node_modules/@nuxt/telemetry/bin/nuxt-telemetry.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/var/app/staging/node_modules/@nuxt/telemetry/bin/nuxt-telemetry.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent `

**Comment by Frou-HOS** [comment]
> > then you should be using v1 of `@nuxt/telemetry`.
> 
> The version 1.3.8 of @nuxt/telemetry generates this error. I tried downgrading to 1.3.7 and everything works ok.

Not working for me.
On gitlab CI/CD if i launch npm install of my nuxt project 
Node image:14.17.6
Nuxt v2.15.8
Telemetry version installed by an other pakage is 1.3.6
Still have this error :
npm ERR! path /builds/[PATH_PROJECT]/node_modules/nuxt/node_modules/@nuxt/telemetry/bin/nuxt-telemetry.js

Add telemetry 1.3.7 in pakage.json didn't correct the error
And disable telemetry in config file didn't correct the error

**Comment by Frou-HOS** [comment]
> Not working for me. On gitlab CI/CD if i launch npm install of my nuxt project Node image:14.17.6 Nuxt v2.15.8 Telemetry version installed by an other pakage is 1.3.6 Still have this error : npm ERR! path /builds/[PATH_PROJECT]/node_modules/nuxt/node_modules/@nuxt/telemetry/bin/nuxt-telemetry.js
> 
> Add telemetry 1.3.7 in pakage.json didn't correct the error And disable telemetry in config file didn't correct the error

with yarn install it's working no more error

**Comment by Mobeidat** [comment]
Any update on this? it's also broken for new Nuxt created apps

**Comment by AikateriniKyriakou** [comment]
> v1.3.8 still depends on ^1.2.0 of rc9: https://unpkg.com/browse/@nuxt/telemetry@1.3.8/package.json.
> 
> Would you provide a reproduction?

I tried to install the package in version 1.3.8 and the same error occured as when I tried to install nuxt v.2.14.12. After that, I tried to install package version 1.3.7 and, then, the nuxt package and its was installed successfully. Also, the nuxt app built successfully. 

Error: 
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /web-app/node_modules/@nuxt/telemetry/bin/nuxt-telemetry.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/web-app/node_modules/@nuxt/telemetry/bin/nuxt-telemetry.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.npm/_logs/2022-11-16T13_33_29_040Z-debug.log

**Comment by erikuit** [comment]
Looks like the dist/ and bin/ folders are missing in my node_modules for version 1.3.8.:

![telemetry138](https://user-images.githubusercontent.com/9920252/202196943-e3ce94b6-ec28-4d2f-80e1-a29bf38cfd64.jpg)

In 1.3.7 they are there. Maybe a problem with the build step?

![telemetry137](https://user-images.githubusercontent.com/9920252/202197115-ae28971d-1f52-488f-b591-66fbfc42115d.jpg)

**Comment by MOHAMMADHMEAD** [comment]
same here

**Comment by kabucya** [comment]
same here

**Comment by ordas** [comment]
Same problem here. Nuxt 2.15.8. Node 18.12.1

**Comment by pi0** [comment]
THere was an issue with npm while releasing `1.x` version for Nuxt 2. Should be fixed in `@nuxt/telemetry@1.3.9` please try upgrading lockfile.

**Comment by elcferreira** [comment]
> THere was an issue with npm while releasing `1.x` version for Nuxt 2. Should be fixed in `@nuxt/telemetry@1.3.9` please try upgrading lockfile.

@pi0 I regenerated my lockfile.

 It's works now, super thanks!

**Comment by ordas** [comment]
It's works now, super thanks! 
1- Delete node_modules and package-lock.json
2- run npm install
