### ISSUE TITLE
Unsure of the ohmyfetch dependency but results in older version of ufo installed - multiple ufo versions installed in my project

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/telemetry#91]
It seems that in my Nuxt 3 project, ohmyfetch is required by this telemetry package.

I'm seeing that ofetch is now on 1.0.0 which uses the latest ufo package.

Currently, vue 3 uses ufo ^1.0.0 while the ohmyfetch version used here uses 0.8.6

But then when trying to install ohmyfetch v1.0.0 it does not exist it seems.

So I'm unsure whether ohmyfetch is the same as ofetch or not.

But the issue I see is that 2 versions of ufo are installed. ^1.0.0 for vue projects, and because of the older version of ohmyfetch here, there is a 2nd ufo package installed at version 0.8.6

Is there a simple dependency update that could be done to resolve multiple versions of the ufo package installing?

**Comment by silverbackdan** [comment]
I've figured out what has changed.

`ohmyfetch` appears to have changed name to `ofetch` and so version `1.0.0` is not available under `ohmyfetch`

It seems Nuxt 3 only needs `ohmyfetch` due to this dependency.

`ohmyfetch` as required here uses an older version of the ufo package.

Would it be possible for this package instead to use the later version of `ofetch`. It means we can keep up to date with dependencies.

I don't know if it means we need to add an alias in to Nuxt 3 projects for `ohmyfetch` to `ofetch` or other breaking changes due to the package name change?

Also the docs could be updated here if the $fetch name may change to ofetch, but I'm not sure there. https://nuxt.com/docs/getting-started/data-fetching#directly-calling-an-api-endpoint

This has only arisen because I get an message letting me know 2 versions of ufo are installed.

Thanks for all your great work.

**Comment by Atinux** [comment]
I guess we can upgrade to `ofetch` @pi0 ?

**Comment by danielroe** [comment]
This should be resolved now.

**Comment by silverbackdan** [comment]
Thanks @danielroe it is indeed, and I updated imports in my module to use the correct package name. I noticed when my tests started failing.
