### ISSUE TITLE
Unable to select "n" as an option in participating

### ISSUE THREAD

**Issue by jwoertink** [nuxt/telemetry#95]
I've never used Nuxt before. This is my first time, and when running `npm install`, it's asking me to participate, but if I type `n`, it just keeps asking me. 

![image](https://user-images.githubusercontent.com/2391/219104716-c148b768-3726-4960-9d78-7852ba1481af.png)

**Comment by jwoertink** [comment]
oh, apparently after typing `n` I just had to hit enter... So I guess the issue here is just the UX of why it keeps repeating the prompt and less of it just not working.. :sweat_smile:

**Comment by danielroe** [comment]
I think that might be an issue within nuxi... cc: @pi0

**Comment by matiasperrone** [comment]
Does not work with Y either.... but hit Enter and "No" is the current selected response

**Comment by MissShim** [comment]
I had the same problem, thank you for sharing the solution!

**Comment by danielroe** [comment]
This should be resolved in the latest release via https://github.com/nuxt/telemetry/pull/103
